services:
  App\Application\EventListener\SomeEventListener:
  App\Application\Http\Handler\HomePage:
  App\Domain\TodosRepository:
    factory: [Antidot\Persistence\Doctrine\Container\EntityRepositoryFactory, 'App\Domain\Model\Todo']
  Antidot\Render\TemplateRenderer:
    factory: [Antidot\Render\Phug\Container\PugRendererFactory]
parameters:
  debug: false
  config_cache_enabled: true
  doctrine:
    connection:
      orm_default:
        params:
          path: var/database.sqlite
  app-events:
    event-listeners:
      App\Application\Event\SomeEvent:
        - App\Application\EventListener\SomeEventListener
  monolog:
    handlers:
      default:
        type: 'stream'
        options:
          stream: 'var/log/%date%-default.log'
          level: 400